module.exports = {
  secret_key: "ygt_secret",
  api_key: "ygt_key",
  base_url: "http://192.168.1.105:5555",
  port: "5555",
  database: {
    development: {
      username: "admin",
      password: "",
      database: "ygt",
      host: "localhost",
      port: "8889",
      dialect: "mysql",
      operatorsAliases: 0,
      timezone: "+03:00",
      logging: false,
    },
    test: {
      username: "admin",
      password: "",
      database: "ygt",
      host: "localhost",
      port: "8889",
      dialect: "mysql",
      operatorsAliases: 0,
      timezone: "+03:00",
      logging: false,
    },
    production: {
      username: "admin",
      password: "",
      database: "ygt",
      host: "localhost",
      port: "8889",
      dialect: "mysql",
      operatorsAliases: 0,
      timezone: "+03:00",
      logging: false,
    },
  },
};
